# Generated by Django 4.0.4 on 2023-12-17 05:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='my_user',
            name='tier',
        ),
    ]
