# Generated by Django 4.1.4 on 2023-12-30 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mainapp", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="my_user",
            name="draws",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="my_user",
            name="losses",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="my_user",
            name="rank",
            field=models.CharField(default=None, max_length=50),
        ),
        migrations.AddField(
            model_name="my_user",
            name="wins",
            field=models.IntegerField(default=0),
        ),
    ]
