# Generated by Django 4.0.4 on 2023-12-17 14:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0002_remove_my_user_tier'),
    ]

    operations = [
        migrations.AddField(
            model_name='my_user',
            name='tier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='mainapp.tier'),
        ),
    ]
