# Generated by Django 4.1.4 on 2023-03-26 07:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("mainapp", "0002_my_user_intetion_to_fight_profile_match"),
    ]

    operations = [
        migrations.DeleteModel(name="Profile",),
    ]
