# Generated by Django 4.0.4 on 2023-08-21 04:41

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0002_remove_my_user_available_time_match'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='match',
            name='my_user',
        ),
        migrations.AddField(
            model_name='match',
            name='player',
            field=models.ManyToManyField(related_name='player_match', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='match',
            name='referee',
            field=models.ManyToManyField(related_name='referee_match', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='match',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
