# Generated by Django 4.1.4 on 2023-03-26 07:43

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mainapp", "0003_delete_profile"),
    ]

    operations = [
        migrations.RemoveField(model_name="match", name="player",),
        migrations.AddField(
            model_name="match",
            name="player1",
            field=models.ManyToManyField(
                related_name="Match_player2", to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
