# Generated by Django 4.0.4 on 2023-09-06 06:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0004_match_gym'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='my_user',
            name='end_date',
        ),
        migrations.RemoveField(
            model_name='my_user',
            name='start_date',
        ),
    ]
