# Generated by Django 4.1.4 on 2023-03-26 07:52

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mainapp", "0004_remove_match_player_match_player1"),
    ]

    operations = [
        migrations.AddField(
            model_name="match",
            name="player2",
            field=models.ManyToManyField(
                related_name="Match_player2", to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AlterField(
            model_name="match",
            name="player1",
            field=models.ManyToManyField(
                related_name="Match_player1", to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
