# Generated by Django 4.0.4 on 2023-09-12 07:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0005_remove_my_user_end_date_remove_my_user_start_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Gym',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gym_name', models.CharField(max_length=50)),
            ],
        ),
        migrations.RemoveField(
            model_name='my_user',
            name='gym',
        ),
        migrations.AlterField(
            model_name='match',
            name='gym',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='mainapp.gym'),
        ),
    ]
