# Generated by Django 4.1.4 on 2023-03-26 11:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("mainapp", "0005_match_player2_alter_match_player1"),
    ]

    operations = [
        migrations.RenameField(
            model_name="my_user",
            old_name="intetion_to_fight",
            new_name="intention_to_fight",
        ),
    ]
