# Generated by Django 4.0.4 on 2023-06-24 06:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0006_rename_intetion_to_fight_my_user_intention_to_fight'),
    ]

    operations = [
        migrations.CreateModel(
            name='Player',
            fields=[
                ('my_user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='my_user', serialize=False, to=settings.AUTH_USER_MODEL)),
                ('score', models.IntegerField(default=1000)),
                ('intention_to_fight', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Refree',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RenameField(
            model_name='my_user',
            old_name='intention_to_fight',
            new_name='is_player',
        ),
        migrations.RemoveField(
            model_name='my_user',
            name='score',
        ),
        migrations.AddField(
            model_name='my_user',
            name='is_refree',
            field=models.BooleanField(default=False),
        ),
        migrations.DeleteModel(
            name='Match',
        ),
    ]
